<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <StartupObject>FandNEL.Program</StartupObject>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <AssemblyName>FandNEL</AssemblyName>
    <RootNamespace>FandNEL</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
    <PackageReference Include="Photino.NET" Version="3.1.18" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../FandNEL.Core/FandNEL.Core.csproj" />
    <ProjectReference Include="../FandNEL.GameLauncher/FandNEL.GameLauncher.csproj" />
    <ProjectReference Include="../FandNEL.Proxy/FandNEL.Proxy.csproj" />
  </ItemGroup>
</Project>
